// Generated by CoffeeScript 1.10.0

/*
    Circle object.

    Written by Bryce Summers on 6/18/2016.
    
    Purpose:
     - This class represents the geometry of a Circle.
 */

(function() {
  BT2D.CircleGeometry = (function() {
    function CircleGeometry() {}

    return CircleGeometry;

  })();

}).call(this);
