// Generated by CoffeeScript 1.10.0

/*
    Frustrum object.

    Written by Bryce Summers on 6/18/2016.
    
    Purpose:
     - This class represents the geometry of individual frustrums,
     - Along with associated starting and ending data and spectrum data.
     
     
    Representation:
     - The Frustrum is represented by 4 2D vector locations, 
       represented by 2 pairs of starting and ending points.
     - the ray start1 -> end1 is represented guranteed to be to the left ( counter-clockwise ) of start2 -> end2
     
     The frustrum is said to be complete then it has all 4 points, but imcomplete it it only has the near points defined.
 */

(function() {
  BT2D.Frustrum = (function() {
    function Frustrum(_start1, _start2, dir1, dir2) {
      this.dir1 = dir1;
      this.dir2 = dir2;
      this.validateOrientation();
      this._start1 = _start1;
      this._start2 = _start2;
      this._end1 = null;
      this._end2 = null;
    }

    Frustrum.prototype.validateOrientation = function() {};

    Frustrum.prototype.complete = function(end1, end2) {
      this._end1 = end1.clone();
      return this._end2 = end2.clone();
    };

    Frustrum.prototype.getStart1 = function() {
      return this._start1;
    };

    Frustrum.prototype.getStart2 = function() {
      return this._start2;
    };

    Frustrum.prototype.getEnd1 = function() {
      return this._end1;
    };

    Frustrum.prototype.getEnd2 = function() {
      return this._end2;
    };

    return Frustrum;

  })();

}).call(this);
