// Generated by CoffeeScript 1.10.0

/*
    Geometry object.

    Written by Bryce Summers on 6/18/2016.
    
    Purpose:
     - This is the super class that defines all geometry objects.
 */

(function() {
  BT2D.Geometry = (function() {
    function Geometry() {}

    Geometry.prototype.intersectRay = function(ray, intersection) {
      console.log("ERROR: BT2D: intersectRay. This method should be overriden.");
      return false;
    };

    return Geometry;

  })();

}).call(this);
