// Generated by CoffeeScript 1.10.0

/*
    Ray object.

    Written by Bryce Summers on 6/18/2016.
    
    Purpose:
     - This class represents a Ray starting at an origination point and
       proceding infinitely out into space in a particular direction.
 */

(function() {
  BT2D.Ray = (function() {
    function Ray(_origin, _direction) {
      this._origin = _origin.clone();
      this._direction = _direction.clone();
    }

    Ray.prototype.getOrigin = function() {
      return this._origin.clone();
    };

    Ray.prototype.getDirection = function() {
      return this._direction.clone();
    };

    Ray.prototype.getPosition = function(time) {
      var location, offset;
      offset = this.getDirection();
      offset.multiplyScalar(time);
      location = this.getOrigin();
      location.add(offset);
      return location;
    };

    Ray.prototype.getType = function() {
      return BT2D.Line.RAY;
    };

    return Ray;

  })();

}).call(this);
