// Generated by CoffeeScript 1.10.0

/*
    Binary Partitioner Interface.

    Written by Bryce Summers on 6/26/2016.
    
    Purpose:
     - Binary Partitioners are able to partition incoming points into the spaces defined by the parttioner.
     - i.e. for a line, the spaces would be the two half planes on either side of the line and the set of all points on the line.
 */

(function() {
  BT2D.BinaryPartitioner = (function() {
    function BinaryPartitioner() {}

    BinaryPartitioner.prototype.side_test = function(pt) {
      console.log("Interface only.");
      debugger;
    };

    BinaryPartitioner.prototype.representative_point = function() {
      console.log("Interface only.");
      debugger;
    };

    BinaryPartitioner.prototype.ray_partition_intersection_time = function(ray) {
      console.log("Interface only.");
      debugger;
    };

    return BinaryPartitioner;

  })();

}).call(this);
