// Generated by CoffeeScript 1.10.0

/*
    Geometry object.

    Written by Bryce Summers on 6/18/2016.
    
    Purpose:
     - This is the super class that defines all geometry objects.
 */

(function() {
  BT2D.Set = (function() {
    function Set() {}

    Set.prototype.add = function(object) {
      console.log("ERROR: BT2D: intersectRay. This method should be overriden.");
      return false;
    };

    Set.prototype.clear = function() {};

    Set.prototype.remove = function(object) {};

    return Set;

  })();

}).call(this);
