// Generated by CoffeeScript 1.10.0
(function() {
  BT2D.Constants = {};

  BT2D.Constants.LEFT = -1;

  BT2D.Constants.ON = 0;

  BT2D.Constants.RIGHT = 1;

  BT2D.Constants.NO_INTERSECTION = null;

  BT2D.Constants.EPSILON = .0000001;

  BT2D.Constants.LIGHT_LENGTH = 40.0;

  BT2D.Constants.MINNIMUM_SCATTER_SEPARATION = 1;

  BT2D.mouse_x = 0.0;

  BT2D.mouse_y = 0.0;

  BT2D.mouse_changed = true;

}).call(this);
