// Generated by CoffeeScript 1.10.0
(function() {
  BT2D.Constants = {};

  BT2D.Constants.LEFT = -1;

  BT2D.Constants.ON = 0;

  BT2D.Constants.RIGHT = 1;

  BT2D.Constants.NO_INTERSECTION = null;

  BT2D.Constants.EPSILON = .0000001;

}).call(this);
