// Generated by CoffeeScript 1.10.0

/*
    Intersection object.

    Written by Bryce Summers on 6/18/2016.
    
    Purpose:
     - This class represents an intersection event.
 */

(function() {
  BT2D.Intersection = (function() {
    function Intersection() {
      this.time = null;
      this.location = null;
      this.surface = null;
    }

    Intersection.prototype.computePosition = function(ray) {
      var offset;
      if (this.time === null) {
        console.log("Error in Intersection, time was null.");
      }
      offset = ray.getDirection().clone();
      offset.multiplyScalar(this.time);
      this.location = ray.getOrigin().clone();
      this.location.add(offset);
      return this.location;
    };

    return Intersection;

  })();

}).call(this);
