// Generated by CoffeeScript 1.10.0

/*
    Intersection object.

    Written by Bryce Summers on 6/18/2016.
    
    Purpose:
     - This class represents an intersection event.
 */

(function() {
  BT2D.Intersection = (function() {
    function Intersection() {
      this.clear();
    }

    Intersection.prototype.clear = function() {
      this.time = null;
      this.location = null;
      return this.surface = null;
    };

    Intersection.prototype.notFound = function() {
      return this.time === null && this.location === null;
    };

    Intersection.prototype.computePosition = function(ray) {
      if (this.time === null || this.time === BT2D.Constants.NO_INTERSECTION) {
        console.log("Error in Intersection, time was null.");
        debugger;
        throw new Error("Error in Intersection, time was null");
      }
      this.location = ray.getPosition(this.time);
      return this.location;
    };

    return Intersection;

  })();

}).call(this);
