// Generated by CoffeeScript 1.10.0

/*
    Beam Tracer Scene object.

    Written by Bryce Summers on 6/18/2016.
    
    Purpose:
     - This class represents and entire 2D Beam Tracer mathematical scene model.
    
    Components:
     - A linearSurfaceSet, which represents the set of surfaces that make up the geometry of the scene.
       This set also keeps a record of emmissive sources of light.
     - A camera that specifies the current view of the scene.
     - A set of Frustrums
 */

(function() {
  BT2D.BeamTracerScene = (function() {
    function BeamTracerScene() {
      this._surfaceSet = new BT2D.SurfaceSet();
      this._lightFrustrumSet = new BT2D.LightFrustrumSet();
      this.frustrumsNeedUpdate = false;
      this._initCamera();
      this._frustrumTracer = new BT2D.FrustrumTracer();
    }

    BeamTracerScene.prototype._initCamera = function() {
      var height, width;
      width = 100;
      height = 100;
      this._camera = new THREE.OrthographicCamera(width / -2, width / 2, height / 2, height / -2, 1, 1000);
      return this._camera.position.z = 2;
    };

    BeamTracerScene.prototype.addSurface = function(surface) {
      this._surfaceSet.addSurface(surface);
      return this.surfacesChanged = true;
    };

    BeamTracerScene.prototype.clearSurfaces = function() {
      this._surfaceSet.clearSurfaces();
      return this.surfacesChanged = true;
    };

    BeamTracerScene.prototype.traceFrustrums = function() {
      if (!this.surfacesChanged) {
        return;
      }
      this._frustrumTracer.traceFrustrums(this._surfaceSet, this._lightFrustrumSet);
      this.surfacesChanged = false;
      return this.frustrumsNeedUpdate = true;
    };

    BeamTracerScene.prototype.frustrumsToTriangles = function(frustrumDrawer) {
      frustrumDrawer.clearTriangles();
      this._lightFrustrumSet.convertToTriangles(frustrumDrawer);
      return this.frustrumsNeedUpdate = false;
    };

    BeamTracerScene.prototype.getCamera = function() {
      return this._camera;
    };

    return BeamTracerScene;

  })();

}).call(this);
