// Generated by CoffeeScript 1.10.0

/*
    binary Space Partitioning Tree.

    Written by Bryce Summers on 6/26/2016.
    
    Purpose:
     - This class enable efficient geometric queries by partitioning planar space using surfaces.
 */

(function() {
  BT2D.BSP = (function() {
    function BSP(surfaceSet) {}

    return BSP;

  })();

}).call(this);
