// Generated by CoffeeScript 1.10.0

/*
    Material

    Written by Bryce Summers on 6/18/2016.
    
    Purpose:
     - This class specifies the Bdrf and other light transport properties of a surface.
     - In otherwords, this class specifies how to an input frustrum with an associated spectrum
       gets transformed into outgoing spectrums.
       
     - Every piece of geometry needs to be associated with a material in order to interact with spectrum frustrums.
     
      * NOTE: Materials should for the most part be read only.
 */

(function() {
  BT2D.Material = (function() {
    function Material(emissive, specular) {
      this.emissive = emissive;
      this.specular = specular;
    }

    Material.prototype.isEmissiveSource = function() {
      return !this.emissive.imperceptible();
    };

    Material.prototype.getSpecularSpectrum = function() {
      return this.specular.clone();
    };

    Material.prototype.getEmmissiveSourceSpectrum = function() {
      return this.emissive.clone();
    };

    return Material;

  })();

}).call(this);
